<!DOCTYPE html>
<!--This file contains header information ususally included at the top of each page to
    provide a universal look -->
<html>
    <head>
        <meta charset="utf-8">
        <meta name="description" content="best lodging near Storm Peak in Silverton Colorado">
        <meta name="viewport" content="width=device-width, initial-scale=1", shrink-to-fit=no">
        
        <!--Required for jQuery to work-->
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
    
        <!--Custom Style Sheets-->
        <link rel="stylesheet" href="hotelstyle.css">
        <link rel="stylesheet" href="slider.css">

        <title><?php echo $page_title; ?></title>
    </head>

    <body>
        <a href = "home.php"><img id="logo" src= "stormpeaklodginglogo.png" alt = "Storm Peak Lodging Logo"></a>
        
        <span id="phone">PH: 1(800) 555-7777</span>

        <nav>
            <ul>
                <li><a href="home.php">Home</a></li>
                <li><a href="reservation.php">Reservation</a></li>
                <li><a href="testimonials.php">Testimonials</a></li>
                <li><a href="about.php">About</a></li>
            </ul>
        </nav>


    